import React from 'react'
import './contact.css'

const contact = () => {
  return (
    <section id='contact'>
      <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Error mollitia reprehenderit repellendus nemo explicabo nostrum enim consectetur rem et, dolore obcaecati architecto deleniti itaque maiores iusto facilis temporibus, alias a doloribus quibusdam ex. Repellat quisquam, itaque ad excepturi eum tenetur ex possimus totam alias et, maiores molestiae fugiat adipisci rem minus dicta voluptate quo molestias. Itaque iusto adipisci velit doloremque asperiores cum omnis! Enim molestias amet eveniet reprehenderit dignissimos, tenetur temporibus, commodi dolorum laboriosam saepe nemo eaque perspiciatis? Quam natus vero quae repudiandae facere laudantium, unde dignissimos voluptatum in quas voluptates inventore ullam suscipit recusandae cumque doloribus sit nisi cum. Labore illo impedit error, qui facilis vero sequi incidunt obcaecati enim temporibus. Delectus, nihil voluptatum quidem consequatur ratione blanditiis. Quibusdam voluptate error eligendi, quod dicta labore! Ad soluta ipsam qui sapiente ducimus! Rerum numquam laborum hic soluta quam pariatur quasi, recusandae sequi placeat minus a tenetur deserunt incidunt in, obcaecati ad voluptatibus, blanditiis saepe? Voluptates provident minima quidem molestiae dolorum? Vitae perferendis ut ab facere a eaque voluptate facilis nulla laudantium? Necessitatibus vero sunt fugiat suscipit iusto, dignissimos ea culpa? Accusantium nisi, at quibusdam incidunt veniam eius nesciunt id vero dolores dolore iure ab architecto rem earum perferendis explicabo possimus saepe porro odio praesentium quaerat. Odio ipsa unde architecto illum porro. Laborum sequi enim, quod nihil dolorum in. Maiores quasi illo earum fuga, esse nesciunt asperiores laudantium ratione natus mollitia quibusdam tenetur expedita, praesentium iusto at debitis reprehenderit, sed eveniet accusantium! Amet adipisci sapiente at consectetur officiis modi? Dolore itaque quidem ipsum esse, quas aperiam ipsam, nihil earum aliquid iure rerum, odio fuga libero. Doloribus hic, ea libero earum architecto dolorem voluptas. Unde sequi, quis aliquam tenetur itaque inventore ex, tempora nobis cum non iure perferendis libero ratione, ea eaque? Officiis, neque expedita suscipit eos odit magnam? Corporis dolorem iure quam molestiae ad quas sequi vero eveniet sint. Nihil accusamus illo, nesciunt aut nam nisi, maxime mollitia quia autem error debitis, ea voluptate ad reiciendis soluta optio blanditiis quae? Fugit perspiciatis enim distinctio ipsam accusamus, eos consequatur quo sapiente incidunt, ad rem labore. Deleniti, iste.</p>
    </section>
  )
}

export default contact